version: '2'


services:
  tor-chain:
    build: ./docker
    volumes: # 鍵のファイルとかを保存する
     - './.tor/:/root/.tor/'
     - 'data:/go'
     - '.:/root/go/src/github.com/Azunyan1111/tor-chain/'
    working_dir: '/root/go/src/github.com/Azunyan1111/tor-chain/app/'
    command: bash -c '/usr/lib/go-1.10/bin/go get -u ./ && /usr/lib/go-1.10/bin/go run main.go'


volumes:
  data:
    driver: 'local'